"""Initial migration

Revision ID: fa739f33bed5
Revises: 
Create Date: 2021-10-11 20:49:59.704043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa739f33bed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regexes', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('regexes', 'name')
    # ### end Alembic commands ###
